model: DiffusionModel
learning_rate: 0.001
batch_size: 32
num_epochs: 100
image_size: 64
num_channels: 3
latent_dim: 128
beta_start: 1e-4
beta_end: 0.02
num_timesteps: 1000
loss_function: "mean_squared_error"
optimizer: "adam"
scheduler:
  type: "cosine"
  warmup_steps: 500
  total_steps: 10000
data:
  dataset_path: "path/to/dataset"
  image_augmentation: true
  normalization: true
logging:
  log_interval: 10
  save_model: true
  model_save_path: "models/diffusion_model.pth"